## A Grandeza da Sétima Arte Produzida No Brasil
## Augusto Buzzoni Calcanhoto

  A idéia era conseguir alguma pesquisa com foco em música, por ser minha prin-
cipal área de interesse. Pensando nisso, peguei a arte brasileira no geral como 
pesquisa, mas, por conta de poucos dados, mudei a intensidade para apenas três 
categorias, mantendo música no projeto. Após uns meses, a quantidade de material
para a pesquisa ainda estava baixa, com exceção aos relacionados ao cinema 
nacional, e com isso a pesquisa tomou outro rumo e se tornou sobre a grandeza da 
sétima arte brasileira em nosso país, sendo o objetivo o mesmo desde o começo: 
mostrar a importância da arte para o Brasil.
  Usando os dados divulgados pela Agência Nacional do Cinema (ANCINE), órgão fe-
deral que cuida de toda a situação dos cinemas brasileiros, e pelo Observatório 
Brasileiro do Cinema e do Audiovisual (OCA), criado pela própria ANCINE para ter
um modo mais fácil de guardar e expor os dados, a pesquisa busca mostrar o 
crescimento do cinema nacional, comparando a arrecadação de obras nacionais e 
internacionais, além de mostrar a importância de apoiar a arte no Brasil como um
todo para aumentar nosso conhecimento cultural e estimular a criação de mais 
programas de incentivo cultural.
  O cenário do cinema estava em um constante crescimento, digo estava, pois o 
momento atual da economia mundial prejudicou esse crescimento nos últimos anos, 
fazendo com que a quantidade de arrecadação fosse menor, mas mesmo assim estamos
conseguindo investir milhões de reais na indústria. O problema é que os filmes 
nacionais não chegam aos pés das produções internacionais em quantidade de arre-
cadação, como por exemplo, no ano de 2017, os filmes nacionais tiveram partici-
pação na renda anual de apenas 8,9%, faturando R$241.406.198,70 , de todo o va-
lor arrecadado, o qual foi R$2.716.236.044,45 , números  referente a indústria 
audiovisual apenas no Brasil.
  Sim, os filmes estrangeiros, principalmente os “blockbusters”, têm uma prepa-
ração, uma produção, muito melhor do que nossos filmes, mas para melhorarmos é
preciso incentivar a indústria brasileira, mostrar que grandes produções serão
recompensadas e, assim, nossa tecnologia voltada a esse ramo vai melhorar e po-
deremos explorar novas idéias que, muitas vezes, são impossíveis pro cinema na-
cional. Existem grandes mentes cinematográficas por aqui, só que em vários mo-
mentos eles encontraram problemas para criar alguma história pela falta de re-
cursos apresentados no Brasil e a pesquisa é para mostrar o nosso crescimento e 
como ele pode ser útil, não só para a indústria, como para a sociedade em
um todo.
  A pesquisa ainda está caminhando a passos curtos, mas pela quantidade de in-
formações que consegui arrumar, creio que será possível sim alcançar o objetivo 
da pesquisa, a qual é mostrar que essa indústria é importante para o desenvolvi-
mento nacional, já que é uma quantia muito grande de renda por ano e parte dela 
é repassada ao governo, e tentar incentivar o culto aos outros ramos da arte 
além da cinematográfica, por ser importante ter essa cultura no ser humano e, 
aqui no Brasil, ainda ser algo fraco.